# --- Stage 1: Build the Frontend ---
FROM node:20-slim AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# --- Stage 2: Final Runtime Image ---
FROM nginx:alpine
# Copy Frontend Build
COPY --from=builder /app/dist /usr/share/nginx/html

# Setup Nginx Configuration
COPY nginx.conf /etc/nginx/nginx.conf

# Expose Nginx Port
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
